### ISSUE TITLE
似乎充不上电

### ISSUE THREAD

**Issue by mywonson** [n00b69/woa-dipper#4]
### Description

如标题所言

### Reproduction steps

```bash
无
```

### Logs

```bash
无
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 on the phone
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Chargint in Windows is problematic on all devices in this project, try;
- Disabling USB host mode
- Using a USB-C to USB-C cable
- Using a fast charging cable
