### ISSUE TITLE
[QUESTION] - <msc dont work>

### ISSUE THREAD

**Issue by Begitdj** [n00b69/woa-dipper#5]
### Question

Im flashed modded ofox
Trying adb shell msc
Device disconnected but dont show in diskpart
Is there any way to fix this?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by Begitdj** [comment]
Im read telegram channel and try using uefi and this is work

**Comment by n00b69** [comment]
Can you check if adb shell msc works if you enable or disable mtp in the mount menu?

**Comment by Begitdj** [comment]
> Can you check if adb shell msc works if you enable or disable mtp in the mount menu?

I try checked it Tomorrow

**Comment by Begitdj** [comment]
> Can you check if adb shell msc works if you enable or disable mtp in the mount menu?

When the MTP is turned on, the MSC operates
