### ISSUE TITLE
[QUESTION] - <Dont boot>

### ISSUE THREAD

**Issue by Begitdj** [n00b69/woa-dipper#6]
### Question

At the first launch after 10 minutes there was a blue screen and loading into Android there I set up dual Boot and tried to launch again as a result at first there was a black screen after several attempts it became frozen On the logo of the Renegade Project and that's it
I did everything according to the instructions. 

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by Begitdj** [comment]
On last version 23h2 another error
File:\\Windows\system32\pdc.sys
Error code: 0xc000007b

**Comment by n00b69** [comment]
Reinstall Windows and make sure to not have any usb cable plugged in while Windows boots for the first time

**Comment by Begitdj** [comment]
> Reinstall Windows and make sure to not have any usb cable plugged in while Windows boots for the first time

I tying and get
Recovery
Your PC couldn't start properly
Aher miluipte tries, the operating system on yout PC failed to start, so it rieeds to
be repaired.
Errer code: Oxc0000001
On 2 attempts i again get 
File:\Windows\system32\driver/pdc.sys
Error code: 0xc000007b

**Comment by Begitdj** [comment]
I tired and get driver pnp watchdog error on first boot and again black screen 

> Reinstall Windows and make sure to not have any usb cable plugged in while Windows boots for the first time

**Comment by Begitdj** [comment]
Sorry, I probably pulled the wire out too late because it worked the second time.
